version: "3.9"
services:
  neo4j:
    image: neo4j:4.4.9-community
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /conf
      - /data
      - /import
      - /logs
      - /plugins
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=none
  api-public:
    build: ./dev-container
    depends_on:
      - neo4j
    ports:
      - 8080:8080
    volumes:
      - ./gropius-backend:/root/gropius-backend:ro
    command: bash -c "./mount-gropius-backend.sh && cd gropius-backend-workdir && gradle api-public:bootRun"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - GROPIUS_API_PUBLIC_JWT_SECRET=ThisIsAnExampleJwtSecretDoNotUseInProduction
      - GROPIUS_API_PUBLIC_DEBUG_NO_AUTHENTICATION=true
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_ADMIN
  api-internal:
    build: ./dev-container
    depends_on:
      - neo4j
    ports:
      - 8081:8081
    volumes:
      - ./gropius-backend:/root/gropius-backend:ro
    command: bash -c "./mount-gropius-backend.sh && cd gropius-backend-workdir && gradle api-internal:bootRun"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SERVER_PORT=8081
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_ADMIN
  dev-login-service:
    image: node:18
    depends_on:
      - api-internal
    ports:
      - 3000:3000
    volumes: 
      - ./dev-login-service:/app
    working_dir: /app
    command: bash -c "npm i && npm run start"
    environment:
      - API_ENDPOINT=http://api-internal:8081/graphql
      - JWT_SECRET=ThisIsAnExampleJwtSecretDoNotUseInProduction
      - JWT_ISSUER=dev-login-service
      - INTERNAL_API_KEY=api_key