name: gropius-dev
services:
  neo4j:
    image: neo4j:5.3.0-community
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /conf
      - /data
      - /import
      - /logs
      - /plugins
    environment:
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_AUTH=none
  api-public:
    build:
      context: ./gropius-backend
      dockerfile: ../production-container/Dockerfile-spring
      args:
        module: api-public
    depends_on:
      - neo4j
    ports:
      - 8080:8080
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - GROPIUS_API_PUBLIC_JWT_SECRET=ThisIsAnExampleJwtSecretDoNotUseInProduction
      - GROPIUS_API_PUBLIC_DEBUG_NO_AUTHENTICATION=true
  api-internal:
    build:
      context: ./gropius-backend
      dockerfile: ../production-container/Dockerfile-spring
      args:
        module: api-internal
    depends_on:
      - neo4j
    ports:
      - 8081:8080
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
  dev-login-service:
    image: node:18
    depends_on:
      - api-internal
    ports:
      - 3000:3000
    volumes: 
      - ./dev-login-service:/app
    working_dir: /app
    command: bash -c "npm i && npm run start"
    environment:
      - API_ENDPOINT=http://api-internal:8080/graphql
      - JWT_SECRET=ThisIsAnExampleJwtSecretDoNotUseInProduction
      - JWT_ISSUER=dev-login-service
      - INTERNAL_API_KEY=api_key
      - GITHUB_DUMMY_PAT=${GITHUB_DUMMY_PAT}
  mongo:
    image: mongo
    profiles:
      - github
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:latest
    profiles:
      - github
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - 8082:8081
    depends_on:
      - mongo
  github:
    build:
      context: ./gropius-backend
      dockerfile: ../production-container/Dockerfile-spring
      args:
        module: github
    depends_on:
      - neo4j
      - mongo
      - dev-login-service
    profiles:
      - github
    command: bash -c "while true; do java -jar ./app.jar; sleep 1h;done"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=gropius
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=root
      - GROPIUS_SYNC_LOGIN_SERVICE_BASE=http://dev-login-service:3000/
      - GROPIUS_SYNC_API_SECRET=TODO_loginSecret
