name: gropius-dev
services:
  neo4j:
    image: neo4j:5.13.0-community
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-conf:/conf
      - neo4j-data:/data
      - neo4j-import:/import
      - neo4j-logs:/logs
      - neo4j-plugins:/plugins
    environment:
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_AUTH=none
      - NEO4J_dbms_directories_run=/run
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
  api-public:
    restart: unless-stopped
    build:
      context: ./gropius-backend
      dockerfile: ../production-container/Dockerfile-spring
      args:
        module: api-public
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - GROPIUS_API_PUBLIC_JWT_SECRET=ThisIsAnExampleJwtSecretDoNotUseInProduction
      - GROPIUS_CORE_ALLOWED_AVATAR_URL_PREFIXES=https://avatars.githubusercontent.com/u/,https://www.gravatar.com/avatar/
      - GROPIUS_API_PUBLIC_DEBUG_NO_AUTHENTICATION=true
  api-internal:
    restart: unless-stopped
    build:
      context: ./gropius-backend
      dockerfile: ../production-container/Dockerfile-spring
      args:
        module: api-internal
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - 8081:8080
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - GROPIUS_CORE_CREATE_INDICES_ON_STARTUP=false
  dev-login-service:
    restart: unless-stopped
    image: node:18
    depends_on:
      - api-internal
    ports:
      - 3000:3000
    volumes: 
      - ./dev-login-service:/app
    working_dir: /app
    command: bash -c "npm i && npm run start"
    environment:
      - API_ENDPOINT=http://api-internal:8080/graphql
      - JWT_SECRET=ThisIsAnExampleJwtSecretDoNotUseInProduction
      - JWT_ISSUER=dev-login-service
      - INTERNAL_API_KEY=api_key
      - GITHUB_DUMMY_PAT=${GITHUB_DUMMY_PAT}
  mongo:
    image: mongo
    profiles:
      - github
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
  mongo-express:
    image: mongo-express:latest
    profiles:
      - github
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - 8082:8081
    depends_on:
      - mongo
  github:
    build:
      context: ./gropius-backend
      dockerfile: ../production-container/Dockerfile-spring
      args:
        module: github
    depends_on:
      - neo4j
      - mongo
      - dev-login-service
    profiles:
      - github
    command: bash -c "while true; do java -jar ./app.jar; sleep 1h;done"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=gropius
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=root
      - GROPIUS_SYNC_LOGIN_SERVICE_BASE=http://dev-login-service:3000/
      - GROPIUS_SYNC_API_SECRET=TODO_loginSecret
volumes:
  neo4j-conf:
  neo4j-data:
  neo4j-import:
  neo4j-logs:
  neo4j-plugins:
  mongo-data:
  mongo-config:
