version: "3.9"
name: gropius-production
services:
  neo4j:
    image: neo4j:4.4.11-community
    restart: unless-stopped
    volumes:
      - /conf
      - /data
      - /import
      - /logs
      - /plugins
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=neo4j/TodoNeo4jPassword
  api-public:
    build:
      context: ./gropius-backend
      dockerfile: ../production-container/Dockerfile-spring
      args:
        module: api-public
    depends_on:
      - neo4j
    ports:
      - 8080:8080
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=TodoNeo4jPassword
      - GROPIUS_API_PUBLIC_JWT_SECRET=TodoLongEnoughAndSecureJwtSecretWithAtLeast256Bit
      - LOGGING_LEVEL_IO_GITHUB_GRAPHGLUE=WARN
  api-internal:
    build:
      context: ./gropius-backend
      dockerfile: ../production-container/Dockerfile-spring
      args:
        module: api-internal
    depends_on:
      - neo4j
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=TodoNeo4jPassword
      - GROPIUS_API_INTERNAL_API_TOKEN=TodoInternalApiToken
      - LOGGING_LEVEL_IO_GITHUB_GRAPHGLUE=WARN
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: TODO_mongo_password
    ports:
      - 27017:27017
  github:
    build:
      context: ./gropius-backend
      dockerfile: ../production-container/Dockerfile-spring
      args:
        module: github
    depends_on:
      - neo4j
      - mongo
    command: bash -c "while true; do java -jar ./app.jar; sleep $GROPIUS_SYNC_GITHUB_INTERVAL;done"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=gropius
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=TODO_mongo_password
      - GROPIUS_SYNC_LOGIN_SERVICE_BASE=http://loginservice:3000/
      - GROPIUS_SYNC_API_SECRET=TODO_loginSecret
      - GROPIUS_SYNC_GITHUB_INTERVAL=1h
