import { existsSync, readFileSync } from 'node:fs'
import { readdir, readFile, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig, type DefaultTheme } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { useSidebar } from 'vitepress-openapi'

/**
 * Every API sidebar is generated by `scripts/docs.mjs`. Loading them lazily keeps the site
 * buildable in a fresh checkout, where nothing has been generated yet.
 */
function generatedSidebar(file: string): DefaultTheme.SidebarItem[] {
    const resolved = fileURLToPath(new URL(file, import.meta.url))
    if (!existsSync(resolved)) return []
    try {
        return JSON.parse(readFileSync(resolved, 'utf8')) as DefaultTheme.SidebarItem[]
    } catch {
        return []
    }
}

const kotlinApi = generatedSidebar('./dokka/sidebar.json')
const loginServiceApi = generatedSidebar('../docs/login-service/typedoc-sidebar.json')
const graphqlPublic = generatedSidebar('./generated/graphql-public.sidebar.json')
const graphqlInternal = generatedSidebar('./generated/graphql-internal.sidebar.json')

/**
 * The REST sidebar is derived from the OpenAPI document itself rather than from files on disk -
 * the operation pages are dynamic routes, so there is nothing to walk.
 */
function restSidebar(): DefaultTheme.SidebarItem[] {
    const file = fileURLToPath(new URL('./generated/login-openapi.json', import.meta.url))
    if (!existsSync(file)) return []
    try {
        const spec = JSON.parse(readFileSync(file, 'utf8'))
        if (!spec.paths || Object.keys(spec.paths).length === 0) return []
        return useSidebar({ spec, linkPrefix: '/rest/operations/' }).generateSidebarGroups()
    } catch {
        return []
    }
}

const rest = restSidebar()

/** The only chunks a page needs before it can render: the framework, the theme, and its own. */
const EAGER_CHUNK = /\/(?:framework|theme)\.[^/]+\.js$|\.lean\.js$/

/**
 * Drops the `<link rel="modulepreload">` tags for chunks that are not needed to render the page.
 *
 * VitePress preloads every dynamic import of the app chunk from every page. Registering mermaid as
 * a global component puts its ~40 diagram renderers in that list, along with katex - 44 tags and
 * 3.9 KB of head on each of 5,500 pages, telling every visitor to fetch 1.4 MB of diagram code
 * whether or not the page contains a diagram. mermaid loads the renderer it needs when it meets a
 * diagram, so none of it belongs in the head.
 *
 * This runs after the build because no hook can remove a head tag - `transformHead` only merges
 * into the existing tags, and `shouldPreload` turns a preload into a prefetch, which is the same
 * bytes and still fetches.
 */
async function dropEagerPreloads(outDir: string, collapsed: Set<string>): Promise<void> {
    const entries = await readdir(outDir, { recursive: true, withFileTypes: true })
    let saved = 0

    for (const entry of entries) {
        if (!entry.isFile() || !entry.name.endsWith('.html')) continue

        const file = path.join(entry.parentPath, entry.name)
        const html = await readFile(file, 'utf8')
        const stripped = html.replace(/<link rel="modulepreload" href="([^"]*)">/g, (tag, href: string) => {
            if (!EAGER_CHUNK.test(href)) {
                saved += tag.length
                return ''
            }

            // A collapsed lean chunk is one line that re-exports the full one, so preload that too
            // rather than let the browser discover it a round trip later.
            const full = href.replace(/\.lean\.js$/, '.js')
            if (full !== href && collapsed.has(path.basename(full))) {
                saved -= tag.length
                return `${tag}<link rel="modulepreload" href="${full}">`
            }
            return tag
        })

        if (stripped !== html) await writeFile(file, stripped)
    }

    console.log(`dropped ${(saved / 1048576).toFixed(1)} MB of modulepreload tags`)
}

/**
 * Collapses the `.lean.js` chunks that are not actually lean into a re-export of the full chunk.
 *
 * VitePress emits two chunks per page: the full one for client-side navigation to it, and a lean
 * one - the page without its content, since on the initial load the content is already in the HTML
 * - that the router imports instead. For the TypeScript reference the lean chunk is 15% of the full
 * one, as intended. For the Kotlin reference it is 95%, because `@graphglue/dokka-vitepress` hands
 * the Dokka HTML to Vue as a `?raw` import, and a raw import is a JS constant rather than markdown
 * content, so there is nothing for the lean transform to strip. Those pages ship their content
 * three times: in the HTML, in the full chunk, and again in the chunk that exists to avoid it.
 *
 * Where the lean chunk saves nothing, pointing it at the full one costs the initial load a redirect
 * to a chunk it would otherwise have fetched verbatim, and saves the copy on disk. Where it does
 * its job, it is left alone.
 */
async function dedupeLeanChunks(outDir: string): Promise<Set<string>> {
    const assetsDir = path.join(outDir, 'assets')
    const entries = await readdir(assetsDir, { withFileTypes: true })
    const collapsed = new Set<string>()
    let saved = 0

    for (const entry of entries) {
        if (!entry.isFile() || !entry.name.endsWith('.lean.js')) continue

        const fullName = entry.name.replace(/\.lean\.js$/, '.js')
        const [lean, full] = await Promise.all([
            stat(path.join(assetsDir, entry.name)),
            stat(path.join(assetsDir, fullName)).catch(() => null)
        ])
        if (!full || lean.size < full.size * 0.8) continue

        // Both chunks export exactly these two names.
        const reexport = `export { __pageData, default } from './${fullName}'\n`
        await writeFile(path.join(assetsDir, entry.name), reexport)
        saved += lean.size - reexport.length
        collapsed.add(fullName)
    }

    console.log(`collapsed ${collapsed.size} lean chunks, ${(saved / 1048576).toFixed(1)} MB`)
    return collapsed
}

/** Falls back to the guide while a section has not been generated, so the nav never dead-ends. */
const linkOr = (items: DefaultTheme.SidebarItem[], link: string) => (items.length > 0 ? link : '/docs/')

export default withMermaid(
    defineConfig({
        title: 'Gropius',
        description:
            'A cross-component issue management system for component-based architectures - backend, login service and GraphQL API documentation.',
        lang: 'en-US',

        srcDir: 'docs',
        cleanUrls: true,
        lastUpdated: true,
        appearance: 'dark',

        // VitePress inlines a hash map of every page into every page. Across the roughly 5,500
        // pages the generated references add up to, that map is ~850 KB - on its own it accounted
        // for 4.6 GB of a 6.3 GB build. Moving it into a chunk of its own also lets browsers cache
        // it once instead of re-downloading it with every page.
        metaChunk: true,

        // Rendering 64 of those pages at a time is a lot of large strings in flight at once.
        buildConcurrency: 8,

        // The site is published to ccims.github.io/gropius-docs.
        base: '/gropius-docs/',

        // The generated API references are large and link to each other by construction, so a
        // broken link there should fail the build rather than ship. The guide does point at a
        // handful of dev-server URLs, which are not reachable from a build and never will be.
        ignoreDeadLinks: [/^https?:\/\/localhost(:\d+)?/],

        head: [
            ['link', { rel: 'icon', href: '/gropius-docs/img/logo.svg', type: 'image/svg+xml' }],
            ['meta', { name: 'theme-color', content: '#00639b' }],
            ['meta', { property: 'og:type', content: 'website' }],
            ['meta', { property: 'og:site_name', content: 'Gropius' }]
        ],

        sitemap: {
            hostname: 'https://ccims.github.io/gropius-docs/'
        },

        buildEnd: async ({ outDir }) => {
            await dropEagerPreloads(outDir, await dedupeLeanChunks(outDir))
        },

        themeConfig: {
            logo: '/img/logo.svg',

            nav: [
                { text: 'Guide', link: '/docs/', activeMatch: '^/docs/' },
                { text: 'Kotlin API', link: linkOr(kotlinApi, '/api/'), activeMatch: '^/api/' },
                {
                    text: 'GraphQL',
                    activeMatch: '^/graphql/',
                    items: [
                        { text: 'Public API', link: linkOr(graphqlPublic, '/graphql/public/') },
                        { text: 'Internal API', link: linkOr(graphqlInternal, '/graphql/internal/') }
                    ]
                },
                {
                    text: 'Login service',
                    activeMatch: '^/(rest|login-service)/',
                    items: [
                        { text: 'REST API', link: '/rest/' },
                        { text: 'TypeScript API', link: linkOr(loginServiceApi, '/login-service/') }
                    ]
                },
                { text: 'GitHub', link: 'https://github.com/ccims' }
            ],

            sidebar: {
                '/docs/': [
                    {
                        text: 'Guide',
                        items: [
                            { text: 'Gropius Backend', link: '/docs/' },
                            { text: 'Modules', link: '/docs/modules' },
                            { text: 'Login Service', link: '/docs/login' },
                            { text: 'How to login', link: '/docs/how-to-login' },
                            { text: 'GitHub sync', link: '/docs/github' },
                            { text: 'Jira sync', link: '/docs/jira' }
                        ]
                    }
                ],
                // Each reference gets its generated tree as-is. DeferredSidebar renders it on the
                // client, so the size of a tree no longer has anything to do with the size of the
                // pages it appears on.
                '/api/': kotlinApi,
                '/graphql/public/': graphqlPublic,
                '/graphql/internal/': graphqlInternal,
                '/login-service/': loginServiceApi,

                '/rest/': [{ text: 'REST API', link: '/rest/', items: rest }]
            },

            search: {
                provider: 'local'
            },

            socialLinks: [{ icon: 'github', link: 'https://github.com/ccims/gropius' }],

            editLink: {
                pattern: 'https://github.com/ccims/gropius/edit/main/website/docs/:path',
                text: 'Edit this page on GitHub'
            },

            outline: [2, 3],

            footer: {
                message: 'Released under the MIT License.',
                copyright: 'Software Quality and Architecture - University of Stuttgart'
            }
        },

        vite: {
            resolve: {
                alias: [
                    {
                        // Renders the sidebar entries on the client instead of into every page's
                        // HTML. See the comment at the top of the component - it is the difference
                        // between shipping the sidebar once and shipping it 5,500 times.
                        //
                        // The pattern has to match the whole specifier, because Vite replaces only
                        // the part that matched. It deliberately does not match VPSidebarGroup.vue,
                        // which the replacement imports, nor the replacement's own filename.
                        find: /^.*\/VPSidebar\.vue$/,
                        replacement: fileURLToPath(new URL('./theme/components/DeferredSidebar.vue', import.meta.url))
                    },
                    {
                        // The same, for the contents of the nav bar's dropdown menus.
                        find: /^.*\/VPFlyout\.vue$/,
                        replacement: fileURLToPath(new URL('./theme/components/DeferredFlyout.vue', import.meta.url))
                    }
                ]
            }
        },

        // VitePress bundles the grammars for every language the docs use - kotlin, graphql,
        // typescript, sh - so only the themes need naming.
        markdown: {
            theme: {
                light: 'github-light',
                dark: 'github-dark'
            }
        },

        mermaid: {
            // C4 diagrams in the guide need the layout config the pages set themselves.
            c4: { diagramMarginY: 20 }
        }
    })
)
