import type { Theme } from 'vitepress'
import DefaultTheme from 'vitepress/theme'
import { useDokka } from '@graphglue/dokka-vitepress/client'
import { theme as openapiTheme, useOpenapi } from 'vitepress-openapi/client'

// Order matters for these three. `base.css` builds the page frame and is meant to lose against
// Dokka's own rules; `dokka.css` is Dokka's stylesheet, scoped to the embedded content; and
// `theme.css` re-skins it in VitePress' design tokens, so it has to come last.
import '@graphglue/dokka-vitepress/base.css'
// Generated by `npm run kotlin` from the Dokka output. `scripts/docs.mjs` writes an empty
// placeholder when the Kotlin docs have not been built, so this import always resolves.
import '../dokka/dokka.css'
import '@graphglue/dokka-vitepress/theme.css'
// Order-independent: styles the generated entries in VitePress' own sidebar.
import '@graphglue/dokka-vitepress/sidebar.css'

import 'vitepress-openapi/dist/style.css'
import './custom.css'

// Written by `npm run rest`; `scripts/docs.mjs` leaves an empty spec behind otherwise.
import spec from '../generated/login-openapi.json'

export default {
    extends: DefaultTheme,
    enhanceApp(ctx) {
        useDokka(ctx.app)

        useOpenapi({ spec })
        openapiTheme.enhanceApp(ctx)
    }
} satisfies Theme
